class CfgPatches {
    class JTG_KPA {
        units[] = {
            "jtg_kpa_rifleman",
            "jtg_kpab_rifleman",
            "O_JTGKPA_Team_Leader",
            "O_JTGKPA_RPG_Specialist",
            "O_JTGKPA_RPG_Assistant"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhs_c_troops",
            "A3_Modules_F",
            "A3_Modules_F_Curator"
        };
        author = "+= rath";
        authors[] = { "+= rath" };
    };
};




//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 174.142559 on Stable branch
// Generated with ALiVE version 1.3.6.1706261
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class JTG_KPA {
        displayName = "North Korean Army";
        side = 0;
        flag = "";
        icon = "\jtg_main\data\flag_kpa.paa";
        priority = 1;
    };
};

class CfgGroups {
    class EAST {

        class JTG_KPA {
            name = "North Korean Army";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class rhs_msv_rifleman;
    class rhs_msv_rifleman_OCimport_01 : rhs_msv_rifleman { scope = 0; class EventHandlers; };
    class rhs_msv_rifleman_OCimport_02 : rhs_msv_rifleman_OCimport_01 { class EventHandlers; };


    class jtg_kpa_rifleman : rhs_msv_rifleman_OCimport_02 {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "JTG_KPA";

        identityTypes[] = { "Head_Asian" , "LanguageENG_F" , "rhs_scarf" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74m_1p63','rhs_acc_dtk1983','','',['rhs_30Rnd_545x39_7N10_AK',30],[],''],[],['rhs_weap_rsp30_red','','','',[],[],''],['jtg_u_kpa_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_epinephrine',1],['ACE_CableTie',1],['ACE_IR_Strobe_Item',1],['ACE_Flashlight_XL50',1],['rhs_30Rnd_545x39_7N10_AK',2,30],['rhs_mag_rgn',1,1]]],['JTG_6b23_kpa_crew',[['rhs_30Rnd_545x39_7N10_AK',5,30],['rhs_mag_rgn',1,1]]],[],'rhs_ssh68','rhs_scarf',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class jtg_kpab_rifleman : rhs_msv_rifleman_OCimport_02 {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (Woodland)";
        side = 0;
        faction = "JTG_KPA";

        identityTypes[] = { "Head_Asian" , "LanguageENG_F" , "rhs_scarf" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74m_1p63','rhs_acc_dtk','','rhs_acc_1p63',['rhs_30Rnd_545x39_7N10_AK',30],[],''],[],['rhs_weap_rsp30_red','','','',[],[],''],['jtg_u_kpab_fatigue_01',[['FirstAidKit',1],['rhs_30Rnd_545x39_7N10_AK',2,30],['rhs_mag_rgn',1,1]]],['JTG_6b23_kpab_crewofficer',[['rhs_30Rnd_545x39_7N10_AK',5,30],['rhs_mag_rgn',1,1]]],[],'JTG_H_ssh68_kpa','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_JTGKPA_Team_Leader : jtg_kpa_rifleman {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "JTG_KPA";

        identityTypes[] = { "Head_Asian" , "LanguageENG_F" , "rhs_scarf" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74','rhs_acc_dtk1983','','',['rhs_30Rnd_545x39_AK',30],[],''],[],['rhs_weap_makarov_pm','','','',['rhs_mag_9x18_8_57N181S',8],[],''],['jtg_u_kpa_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_epinephrine',1],['rhs_mag_rgn',1,1],['rhs_mag_9x18_8_57N181S',2,8]]],['JTG_6b23_kpab_6sh92',[['rhs_mag_rgn',1,1],['rhs_30Rnd_545x39_AK',10,30]]],['tf_bussole',[['rhs_mag_rdg2_black',2,1],['rhs_mag_rgd5',1,1]]],'rhs_ssh68','rhs_scarf',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_JTGKPA_RPG_Specialist : jtg_kpa_rifleman {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "RPG Specialist";
        side = 0;
        faction = "JTG_KPA";

        identityTypes[] = { "Head_Asian" , "LanguageENG_F" , "rhs_scarf" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74m_1p63','rhs_acc_dtk1983','','',['rhs_30Rnd_545x39_7N10_AK',30],[],''],['rhs_weap_rpg7','','','',['rhs_rpg7_PG7VL_mag',1],[],''],['rhs_weap_rsp30_red','','','',[],[],''],['jtg_u_kpab_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_epinephrine',1],['ACE_CableTie',1],['ACE_IR_Strobe_Item',1],['ACE_Flashlight_XL50',1],['rhs_mag_rgn',1,1],['30Rnd_545x39_Mag_Tracer_Green_F',2,30]]],['JTG_6b23_kpa',[['30Rnd_545x39_Mag_Tracer_Green_F',2,30]]],['rhs_rpg_empty',[['rhs_rpg7_PG7VL_mag',2,1],['30Rnd_545x39_Mag_Tracer_Green_F',4,30],['rhs_rpg7_OG7V_mag',1,1]]],'rhs_ssh68','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_JTGKPA_RPG_Assistant : O_JTGKPA_RPG_Specialist {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "RPG Assistant";
        side = 0;
        faction = "JTG_KPA";

        identityTypes[] = { "Head_Asian" , "LanguageENG_F" , "rhs_scarf" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74','rhs_acc_dtk1983','','',['rhs_30Rnd_545x39_AK',30],[],''],[],['rhs_weap_rsp30_red','','','',[],[],''],['jtg_u_kpab_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_epinephrine',1],['ACE_CableTie',1],['ACE_IR_Strobe_Item',1],['ACE_Flashlight_XL50',1],['rhs_mag_rgn',1,1],['rhs_30Rnd_545x39_AK',1,30]]],['JTG_6b23_kpa',[['rhs_30Rnd_545x39_AK',2,30]]],['rhs_rpg_empty',[['30Rnd_545x39_Mag_Tracer_Green_F',6,30],['rhs_rpg7_PG7VL_mag',2,1]]],'rhs_ssh68','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};