class CfgPatches {
    class JTG_TRK {
        units[] = {
            "B_JTGTRK_Rifleman",
            "B_JTGTRK_Rifleman_AT",
            "B_JTGTRK_Machinegunner",
            "B_JTGTRK_MG_Assistant",
            "B_JTGTRK_Team_Leader",
            "B_JTGTRK_Rifleman_GL",
            "B_JTGTRK_Rifleman_SAW"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhs_c_troops"
        };
        author = "+= rath";
        authors[] = { "+= rath" };
    };
};




//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 174.142559 on Stable branch
// Generated with ALiVE version 1.3.6.1706261
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class JTG_TRK {
        displayName = "Turkish Army";
        side = 1;
        flag = "";
        icon = "\jtg_main\data\flag_trk.paa";
        priority = 1;
    };
};

class CfgGroups {
    class WEST {

        class JTG_TRK {
            name = "Turkish Army";

            class Infantry {
                name = "Infantry";

                class jtgtrk_infantry_fireteam {
                    name = "Fireteam";
                    side = 1;
                    faction = "JTG_TRK";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_JTGTRK_Team_Leader";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_JTGTRK_Rifleman_SAW";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_JTGTRK_Rifleman_AT";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_JTGTRK_Rifleman_AT";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_JTGTRK_Rifleman_GL";
                    };
                };

                class jtgtrk_infantry_machinegun_team {
                    name = "Machinegun Team";
                    side = 1;
                    faction = "JTG_TRK";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_JTGTRK_Team_Leader";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_JTGTRK_Machinegunner";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_JTGTRK_MG_Assistant";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class jtg_trk_infantry_rifleman;
    class jtg_trk_infantry_rifleman_OCimport_01 : jtg_trk_infantry_rifleman { scope = 0; class EventHandlers; };
    class jtg_trk_infantry_rifleman_OCimport_02 : jtg_trk_infantry_rifleman_OCimport_01 { class EventHandlers; };

    class ;


    class B_JTGTRK_Rifleman : jtg_trk_infantry_rifleman_OCimport_02 {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_hk416d10_LMT_d','','','',['rhs_mag_30Rnd_556x45_Mk318_Stanag',30],[],''],[],[],['jtg_u_trk_fatigue_01',[['FirstAidKit',2]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['rhs_mag_an_m8hc',2,1]]],['B_AssaultPack_rgr',[['rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red',10,30]]],'jtg_h_6b27m_trk','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_Rifleman_AT : B_JTGTRK_Rifleman {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_hk416d10_LMT_d','','','',['rhs_mag_30Rnd_556x45_Mk318_Stanag',30],[],''],['rhs_weap_rpg26','','','',['rhs_rpg26_mag',1],[],''],[],['jtg_u_trk_fatigue_01',[['FirstAidKit',2]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['rhs_mag_an_m8hc',2,1],['rhs_rpg26_mag',1,1]]],['B_AssaultPack_rgr',[['rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red',10,30]]],'jtg_h_6b27m_trk','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    // class B_JTGTRK_Machinegunner : B_JTGTRK_Rifleman {
    //     author = "+= rath";
    //     scope = 2;
    //     scopeCurator = 2;
    //     displayName = "Machinegunner";
    //     side = 1;
    //     faction = "JTG_TRK";

    //     identityTypes[] = { "Head_TK" , "LanguageENG_F" };

    //     class EventHandlers : EventHandlers {
    //         class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

    //         class ALiVE_orbatCreator {
    //         };

    //     };

    //     // custom attributes (do not delete)
    //     ALiVE_orbatCreator_owned = 1;

    // };

    class B_JTGTRK_MG_Assistant : B_JTGTRK_Rifleman {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "MG Assistant";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_hk416d10_LMT_d','','','',['rhs_mag_30Rnd_556x45_Mk318_Stanag',30],[],''],[],['rhsusf_weap_m9','','','',['rhsusf_mag_15Rnd_9x19_JHP',15],[],''],['jtg_u_trk_fatigue_01',[['FirstAidKit',2],['rhsusf_mag_15Rnd_9x19_JHP',3,15]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['rhs_mag_an_m8hc',2,1]]],['B_Kitbag_rgr',[['rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red',8,30]]],'jtg_h_6b27m_trk','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_Team_Leader : B_JTGTRK_Rifleman {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_hk416d145_m320','','','',['rhs_mag_30Rnd_556x45_Mk318_Stanag',30],[],''],[],[],['jtg_u_trk_fatigue_01',[['FirstAidKit',2],['rhs_mag_30Rnd_556x45_Mk318_Stanag',1,30]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['rhs_mag_an_m8hc',2,1],['rhs_mag_M441_HE',4,1]]],['tf_rt1523g_black',[['rhs_mag_m714_White',4,1],['rhs_mag_m715_Green',2,1],['rhs_mag_m713_Red',2,1],['rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red',6,30]]],'jtg_h_6b27m_trk','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_Rifleman_GL : B_JTGTRK_Rifleman {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (GL)";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_hk416d145_m320','','','',['rhs_mag_30Rnd_556x45_Mk318_Stanag',30],[],''],[],[],['jtg_u_trk_fatigue_01',[['FirstAidKit',2],['rhs_mag_30Rnd_556x45_Mk318_Stanag',1,30]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['rhs_mag_an_m8hc',2,1],['rhs_mag_30Rnd_556x45_Mk318_Stanag',2,30]]],['B_Carryall_cbr',[['1Rnd_HE_Grenade_shell',20,1],['rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red',20,30]]],'jtg_h_6b27m_trk','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_Rifleman_SAW : B_JTGTRK_Rifleman {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (SAW)";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_lmg_M249E2','','','',['hlc_200rnd_556x45_M_SAW',200],[],''],[],[],['jtg_u_trk_fatigue_01',[['FirstAidKit',2]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['rhs_mag_an_m8hc',2,1]]],['B_Kitbag_rgr',[['200Rnd_556x45_Box_Tracer_F',5,200]]],'jtg_h_6b27m_trk','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};