#include "cfgPatches.hpp"


//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 174.142559 on Stable branch
// Generated with ALiVE version 1.3.6.1706261
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class JTG_TRK {
        displayName = "Turkish Army";
        side = 1;
        flag = "";
        icon = "\jtg_main\data\flag_trk.paa";
        priority = 1;
    };
};

class CfgGroups {
    class WEST {

        class JTG_TRK {
            name = "Turkish Army";

            class Infantry {
                name = "Infantry";

                class jtgtrk_infantry_fireteam {
                    name = "Fireteam";
                    side = 1;
                    faction = "JTG_TRK";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_JTGTRK_Team_Leader";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_JTGTRK_Rifleman_SAW";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_JTGTRK_Rifleman_AT";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_JTGTRK_Rifleman_AT";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_JTGTRK_Rifleman_GL";
                    };
                };

                class jtgtrk_infantry_machinegun_team {
                    name = "Machinegun Team";
                    side = 1;
                    faction = "JTG_TRK";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_JTGTRK_Team_Leader";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_JTGTRK_Machinegunner";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_JTGTRK_MG_Assistant";
                    };
                };

                class jtgtrk_infantry_hq {
                    name = "HQ";
                    side = 1;
                    faction = "JTG_TRK";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "CAPTAIN";
                        side = 1;
                        vehicle = "B_JTGTRK_Officer";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "B_JTGTRK_2IC";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "B_JTGTRK_FAC";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class rhs_vdv_rifleman;
    class rhs_vdv_rifleman_OCimport_01 : rhs_vdv_rifleman { scope = 0; class EventHandlers; };
    class rhs_vdv_rifleman_OCimport_02 : rhs_vdv_rifleman_OCimport_01 { class EventHandlers; };

    class B_JTGTRK_Rifleman;
    class B_JTGTRK_Rifleman_OCimport_01 : B_JTGTRK_Rifleman { scope = 0; class EventHandlers; };
    class B_JTGTRK_Rifleman_OCimport_02 : B_JTGTRK_Rifleman_OCimport_01 { class EventHandlers; };


    class jtg_trk_infantry_rifleman : rhs_vdv_rifleman_OCimport_02 {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_rifle_hk33a2','','','',['hlc_30rnd_556x45_b_HK33',30],[],''],[],[],['jtg_u_trk_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_epinephrine',1]]],['jtg_v_6b5_trk',[['ACE_IR_Strobe_Item',1],['MiniGrenade',2,1],['SmokeShellRed',2,1],['SmokeShellGreen',2,1],['SmokeShell',2,1]]],['B_AssaultPack_rgr',[['ACE_EntrenchingTool',1],['hlc_30rnd_556x45_t_HK33',10,30]]],'jtg_h_6b27m_trk','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_Rifleman_SAW : B_JTGTRK_Rifleman_OCimport_02 {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (SAW)";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_lmg_M249E2','','','',['hlc_200rnd_556x45_M_SAW',200],[],''],[],[],['jtg_u_trk_fatigue_01',[['FirstAidKit',2]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['rhs_mag_an_m8hc',2,1]]],['B_Kitbag_rgr',[['200Rnd_556x45_Box_Tracer_F',5,200]]],'jtg_h_6b27m_trk','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_Rifleman_AT : jtg_trk_infantry_rifleman {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_Euro" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_rifle_hk33a2','','','',['hlc_30rnd_556x45_b_HK33',30],[],''],['rhs_weap_rpg26','','','',['rhs_rpg26_mag',1],[],''],[],['jtg_u_trk_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_epinephrine',1]]],['jtg_v_6b5_trk',[['ACE_IR_Strobe_Item',1],['MiniGrenade',2,1],['SmokeShellRed',2,1],['SmokeShellGreen',2,1],['SmokeShell',2,1],['rhs_rpg26_mag',1,1]]],['B_AssaultPack_rgr',[['ACE_EntrenchingTool',1],['hlc_30rnd_556x45_t_HK33',10,30]]],'jtg_h_6b27m_trk','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_MG_Assistant : B_JTGTRK_Rifleman_OCimport_02 {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "MG Assistant";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_rifle_hk33a2','','','',['hlc_30rnd_556x45_b_HK33',30],[],''],[],['rhsusf_weap_m9','','','',['rhsusf_mag_15Rnd_9x19_JHP',15],[],''],['jtg_u_trk_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['rhsusf_mag_15Rnd_9x19_JHP',3,15]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['rhs_mag_an_m8hc',2,1],['hlc_30rnd_556x45_b_HK33',2,30]]],['B_Kitbag_rgr',[['hlc_30rnd_556x45_t_HK33',10,30],['hlc_100Rnd_792x57_AP_MG42',3,100]]],'jtg_h_6b27m_trk','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_Team_Leader : B_JTGTRK_Rifleman_OCimport_02 {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_rifle_hk33a2RIS_GL','','','',['hlc_30rnd_556x45_b_HK33',30],['rhs_mag_M441_HE',1],''],[],['rhsusf_weap_m9','','','',['rhsusf_mag_15Rnd_9x19_JHP',15],[],''],['jtg_u_trk_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_IR_Strobe_Item',1],['ACE_epinephrine',1],['rhsusf_mag_15Rnd_9x19_JHP',2,15],['hlc_30rnd_556x45_t_HK33',2,30]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['hlc_30rnd_556x45_t_HK33',3,30],['SmokeShell',2,1]]],['tf_rt1523g_black',[['rhs_mag_m714_White',4,1],['rhs_mag_m715_Green',2,1],['rhs_mag_m713_Red',2,1],['1Rnd_HE_Grenade_shell',4,1],['hlc_30rnd_556x45_t_HK33',4,30]]],'jtg_h_6b27m_trk','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_Rifleman_GL : B_JTGTRK_Rifleman_OCimport_02 {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (GL)";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_rifle_hk33a2RIS_GL','','','',['hlc_30rnd_556x45_b_HK33',30],['1Rnd_HE_Grenade_shell',1],''],[],[],['jtg_u_trk_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_epinephrine',1],['ACE_IR_Strobe_Item',1]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['rhs_mag_an_m8hc',2,1]]],['B_Carryall_cbr',[['1Rnd_HE_Grenade_shell',18,1],['hlc_30rnd_556x45_t_HK33',20,30],['1Rnd_SmokeRed_Grenade_shell',2,1],['1Rnd_SmokeGreen_Grenade_shell',2,1],['1Rnd_Smoke_Grenade_shell',3,1],['UGL_FlareRed_F',2,1]]],'jtg_h_6b27m_trk','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_Machinegunner : jtg_trk_infantry_rifleman {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machinegunner";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_lmg_mg42kws_b','','','',['hlc_50Rnd_792x57_B_MG42',50],[],''],[],['rhsusf_weap_m9','','','',['rhsusf_mag_15Rnd_9x19_JHP',15],[],''],['jtg_u_trk_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_epinephrine',1],['rhsusf_mag_15Rnd_9x19_JHP',3,15]]],['jtg_v_6b5_trk',[['ACE_IR_Strobe_Item',1],['MiniGrenade',2,1],['SmokeShellRed',2,1],['SmokeShellGreen',2,1],['SmokeShell',2,1]]],['B_AssaultPack_rgr',[['ACE_EntrenchingTool',1],['hlc_100Rnd_792x57_AP_MG42',3,100]]],'jtg_h_6b27m_trk','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_Officer : B_JTGTRK_Team_Leader {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_rifle_hk33a2RIS_GL','','','',['hlc_30rnd_556x45_b_HK33',30],['rhs_mag_M441_HE',1],''],[],['rhsusf_weap_m9','','','',['rhsusf_mag_15Rnd_9x19_JHP',15],[],''],['jtg_u_trk_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_IR_Strobe_Item',1],['ACE_epinephrine',1],['rhsusf_mag_15Rnd_9x19_JHP',2,15],['hlc_30rnd_556x45_t_HK33',2,30]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['hlc_30rnd_556x45_t_HK33',3,30],['SmokeShell',2,1]]],['tf_rt1523g_black',[['rhs_mag_m714_White',4,1],['rhs_mag_m715_Green',2,1],['rhs_mag_m713_Red',2,1],['1Rnd_HE_Grenade_shell',4,1],['hlc_30rnd_556x45_t_HK33',4,30]]],'jtg_h_booniehat_trk','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_2IC : B_JTGTRK_Officer {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "2IC";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_rifle_hk33a2RIS_GL','','','',['hlc_30rnd_556x45_b_HK33',30],['rhs_mag_M441_HE',1],''],[],['rhsusf_weap_m9','','','',['rhsusf_mag_15Rnd_9x19_JHP',15],[],''],['jtg_u_trk_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_IR_Strobe_Item',1],['ACE_epinephrine',1],['rhsusf_mag_15Rnd_9x19_JHP',2,15],['hlc_30rnd_556x45_t_HK33',2,30]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['hlc_30rnd_556x45_t_HK33',3,30],['SmokeShell',2,1]]],['tf_rt1523g_black',[['rhs_mag_m714_White',4,1],['rhs_mag_m715_Green',2,1],['rhs_mag_m713_Red',2,1],['1Rnd_HE_Grenade_shell',4,1],['hlc_30rnd_556x45_t_HK33',4,30]]],'jtg_h_booniehat_trk','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_JTGTRK_FAC : B_JTGTRK_Officer {
        author = "+= rath";
        scope = 2;
        scopeCurator = 2;
        displayName = "FAC";
        side = 1;
        faction = "JTG_TRK";

        identityTypes[] = { "Head_TK" , "LanguageENG_F" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['hlc_rifle_hk33a2RIS_GL','','','',['hlc_30rnd_556x45_b_HK33',30],['rhs_mag_M441_HE',1],''],[],['rhsusf_weap_m9','','','',['rhsusf_mag_15Rnd_9x19_JHP',15],[],''],['jtg_u_trk_fatigue_01',[['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_IR_Strobe_Item',1],['ACE_epinephrine',1],['rhsusf_mag_15Rnd_9x19_JHP',2,15],['hlc_30rnd_556x45_t_HK33',2,30]]],['jtg_v_6b5_trk',[['MiniGrenade',2,1],['SmokeShellGreen',2,1],['SmokeShellRed',2,1],['hlc_30rnd_556x45_t_HK33',3,30],['SmokeShell',2,1]]],['tf_rt1523g_black',[['tfw_dd',1],['rhs_mag_m714_White',2,1],['rhs_mag_m715_Green',2,1],['rhs_mag_m713_Red',2,1],['1Rnd_HE_Grenade_shell',4,1],['hlc_30rnd_556x45_t_HK33',4,30]]],'jtg_h_booniehat_trk','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};